---
- name: install apache2
  apt:
   name: apache2
   state: latest
- name: start apache
  service:
   name: apache2
   state: started
- name: copy index.html file
  copy:
   src: index.html
   dest: /var/www/html/

